--
-- 建筑表.csv
-- 建筑编号编号 = id
-- 建筑名 = name
-- 建筑类型 = type
-- 建筑类别区分 = classify
-- 建筑2级类型 = kind
-- 等级 = lv
-- 建造需要角色等级 = needLv
-- 建筑级别 = jianzhuLv
-- 点击音效 = music
-- 人物是否可以路过 = isway
-- 是否属于地板 = isFloor
-- 占地面积 = size
-- 粒子编号 = particle
-- 购买价格 = needMoney
-- 价格类型 = needType
-- 繁荣度 = prosperity
-- 建筑图片 = img
-- 建筑最大数量 = maxCount
-- 是否可拆除 = delete
-- 是否可建造 = canBuild
-- 是否可移动 = canMoveBuild
-- 建筑点击是否会跳动 = jumpBuild
-- 建筑描述 = buildDesc
-- 建筑信息 = buildFuncitonId
-- 生产类型 = typesOfManufacturing
-- 编辑器动画 = hasAction
-- 子序列 = order
-- 新手ID = xsId
-- 是否可旋转 = canFlip
-- 是否是障碍 = barrier

local data = {
    [1000] = {["id"] = 1000, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 200, ["img"] = "1000", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1001] = {["id"] = 1001, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 2, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 600, ["img"] = "1000", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1002] = {["id"] = 1002, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 3, ["needLv"] = 1, ["jianzhuLv"] = "3", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 1200, ["img"] = "1000", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1003] = {["id"] = 1003, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 4, ["needLv"] = 1, ["jianzhuLv"] = "4", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 2000, ["img"] = "1001", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1004] = {["id"] = 1004, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 5, ["needLv"] = 1, ["jianzhuLv"] = "5", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 3000, ["img"] = "1001", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1005] = {["id"] = 1005, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 6, ["needLv"] = 1, ["jianzhuLv"] = "6", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 4200, ["img"] = "1001", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1006] = {["id"] = 1006, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 7, ["needLv"] = 1, ["jianzhuLv"] = "7", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 5600, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1007] = {["id"] = 1007, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 8, ["needLv"] = 1, ["jianzhuLv"] = "8", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 7200, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1008] = {["id"] = 1008, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 9, ["needLv"] = 1, ["jianzhuLv"] = "9", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 9000, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1009] = {["id"] = 1009, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 10, ["needLv"] = 1, ["jianzhuLv"] = "10", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 11000, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1010] = {["id"] = 1010, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 11, ["needLv"] = 1, ["jianzhuLv"] = "11", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 13200, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1011] = {["id"] = 1011, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 12, ["needLv"] = 1, ["jianzhuLv"] = "12", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 15600, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1012] = {["id"] = 1012, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 13, ["needLv"] = 1, ["jianzhuLv"] = "13", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 18200, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1013] = {["id"] = 1013, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 14, ["needLv"] = 1, ["jianzhuLv"] = "14", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 21000, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1014] = {["id"] = 1014, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 15, ["needLv"] = 1, ["jianzhuLv"] = "15", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 24000, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1015] = {["id"] = 1015, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 16, ["needLv"] = 1, ["jianzhuLv"] = "16", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 27200, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1016] = {["id"] = 1016, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 17, ["needLv"] = 1, ["jianzhuLv"] = "17", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 30600, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1017] = {["id"] = 1017, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 18, ["needLv"] = 1, ["jianzhuLv"] = "18", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 34200, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1018] = {["id"] = 1018, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 19, ["needLv"] = 1, ["jianzhuLv"] = "19", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 38000, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1019] = {["id"] = 1019, ["name"] = "宅邸", ["type"] = 1, ["classify"] = 1, ["kind"] = 1, ["lv"] = 20, ["needLv"] = 1, ["jianzhuLv"] = "20", ["music"] = 1055, ["isway"] = false, ["size"] = {4, 4}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 42000, ["img"] = "1002", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "您的主宅邸。", ["buildFuncitonId"] = {101}, ["order"] = 1, ["canFlip"] = true},
    [1100] = {["id"] = 1100, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 200, ["img"] = "1100", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1101] = {["id"] = 1101, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 2, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 600, ["img"] = "1100", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1102] = {["id"] = 1102, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 3, ["needLv"] = 1, ["jianzhuLv"] = "3", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 1200, ["img"] = "1100", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1103] = {["id"] = 1103, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 4, ["needLv"] = 1, ["jianzhuLv"] = "4", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 2000, ["img"] = "1101", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1104] = {["id"] = 1104, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 5, ["needLv"] = 1, ["jianzhuLv"] = "5", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 3000, ["img"] = "1101", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1105] = {["id"] = 1105, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 6, ["needLv"] = 1, ["jianzhuLv"] = "6", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 4200, ["img"] = "1101", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1106] = {["id"] = 1106, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 7, ["needLv"] = 1, ["jianzhuLv"] = "7", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 5600, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1107] = {["id"] = 1107, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 8, ["needLv"] = 1, ["jianzhuLv"] = "8", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 7200, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1108] = {["id"] = 1108, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 9, ["needLv"] = 1, ["jianzhuLv"] = "9", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 9000, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1109] = {["id"] = 1109, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 10, ["needLv"] = 1, ["jianzhuLv"] = "10", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 11000, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1110] = {["id"] = 1110, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 11, ["needLv"] = 1, ["jianzhuLv"] = "11", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 13200, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1111] = {["id"] = 1111, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 12, ["needLv"] = 1, ["jianzhuLv"] = "12", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 15600, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1112] = {["id"] = 1112, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 13, ["needLv"] = 1, ["jianzhuLv"] = "13", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 18200, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1113] = {["id"] = 1113, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 14, ["needLv"] = 1, ["jianzhuLv"] = "14", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 21000, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1114] = {["id"] = 1114, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 15, ["needLv"] = 1, ["jianzhuLv"] = "15", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 24000, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1115] = {["id"] = 1115, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 16, ["needLv"] = 1, ["jianzhuLv"] = "16", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 27200, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1116] = {["id"] = 1116, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 17, ["needLv"] = 1, ["jianzhuLv"] = "17", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 30600, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1117] = {["id"] = 1117, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 18, ["needLv"] = 1, ["jianzhuLv"] = "18", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 34200, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1118] = {["id"] = 1118, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 19, ["needLv"] = 1, ["jianzhuLv"] = "19", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 38000, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1119] = {["id"] = 1119, ["name"] = "鲜花房", ["type"] = 2, ["classify"] = 1, ["kind"] = 1, ["lv"] = 20, ["needLv"] = 1, ["jianzhuLv"] = "20", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 42000, ["img"] = "1102", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的鲜花房可用于收集和赠送鲜花。", ["buildFuncitonId"] = {101, 131}, ["order"] = 2, ["canFlip"] = true},
    [1200] = {["id"] = 1200, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 200, ["img"] = "1200", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1201] = {["id"] = 1201, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 2, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 600, ["img"] = "1200", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1202] = {["id"] = 1202, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 3, ["needLv"] = 1, ["jianzhuLv"] = "3", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 1200, ["img"] = "1200", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1203] = {["id"] = 1203, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 4, ["needLv"] = 1, ["jianzhuLv"] = "4", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 2000, ["img"] = "1201", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1204] = {["id"] = 1204, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 5, ["needLv"] = 1, ["jianzhuLv"] = "5", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 3000, ["img"] = "1201", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1205] = {["id"] = 1205, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 6, ["needLv"] = 1, ["jianzhuLv"] = "6", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 4200, ["img"] = "1201", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1206] = {["id"] = 1206, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 7, ["needLv"] = 1, ["jianzhuLv"] = "7", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 5600, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1207] = {["id"] = 1207, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 8, ["needLv"] = 1, ["jianzhuLv"] = "8", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 7200, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1208] = {["id"] = 1208, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 9, ["needLv"] = 1, ["jianzhuLv"] = "9", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 9000, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1209] = {["id"] = 1209, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 10, ["needLv"] = 1, ["jianzhuLv"] = "10", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 11000, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1210] = {["id"] = 1210, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 11, ["needLv"] = 1, ["jianzhuLv"] = "11", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 13200, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1211] = {["id"] = 1211, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 12, ["needLv"] = 1, ["jianzhuLv"] = "12", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 15600, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1212] = {["id"] = 1212, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 13, ["needLv"] = 1, ["jianzhuLv"] = "13", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 18200, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1213] = {["id"] = 1213, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 14, ["needLv"] = 1, ["jianzhuLv"] = "14", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 21000, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1214] = {["id"] = 1214, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 15, ["needLv"] = 1, ["jianzhuLv"] = "15", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 24000, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1215] = {["id"] = 1215, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 16, ["needLv"] = 1, ["jianzhuLv"] = "16", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 27200, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1216] = {["id"] = 1216, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 17, ["needLv"] = 1, ["jianzhuLv"] = "17", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 30600, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1217] = {["id"] = 1217, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 18, ["needLv"] = 1, ["jianzhuLv"] = "18", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 34200, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1218] = {["id"] = 1218, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 19, ["needLv"] = 1, ["jianzhuLv"] = "19", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 38000, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1219] = {["id"] = 1219, ["name"] = "许愿池", ["type"] = 3, ["classify"] = 1, ["kind"] = 1, ["lv"] = 20, ["needLv"] = 1, ["jianzhuLv"] = "20", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 42000, ["img"] = "1202", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "许愿池，若想获得更多铜钱，在许愿池许下一个愿望。", ["buildFuncitonId"] = {101, 132}, ["typesOfManufacturing"] = 1, ["order"] = 3, ["canFlip"] = true},
    [1300] = {["id"] = 1300, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 200, ["img"] = "1300", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1301] = {["id"] = 1301, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 2, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 600, ["img"] = "1300", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1302] = {["id"] = 1302, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 3, ["needLv"] = 1, ["jianzhuLv"] = "3", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 1200, ["img"] = "1300", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1303] = {["id"] = 1303, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 4, ["needLv"] = 1, ["jianzhuLv"] = "4", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 2000, ["img"] = "1301", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1304] = {["id"] = 1304, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 5, ["needLv"] = 1, ["jianzhuLv"] = "5", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 3000, ["img"] = "1301", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1305] = {["id"] = 1305, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 6, ["needLv"] = 1, ["jianzhuLv"] = "6", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 4200, ["img"] = "1301", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1306] = {["id"] = 1306, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 7, ["needLv"] = 1, ["jianzhuLv"] = "7", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 5600, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1307] = {["id"] = 1307, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 8, ["needLv"] = 1, ["jianzhuLv"] = "8", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 7200, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1308] = {["id"] = 1308, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 9, ["needLv"] = 1, ["jianzhuLv"] = "9", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 9000, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1309] = {["id"] = 1309, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 10, ["needLv"] = 1, ["jianzhuLv"] = "10", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 11000, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1310] = {["id"] = 1310, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 11, ["needLv"] = 1, ["jianzhuLv"] = "11", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 13200, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1311] = {["id"] = 1311, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 12, ["needLv"] = 1, ["jianzhuLv"] = "12", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 15600, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1312] = {["id"] = 1312, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 13, ["needLv"] = 1, ["jianzhuLv"] = "13", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 18200, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1313] = {["id"] = 1313, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 14, ["needLv"] = 1, ["jianzhuLv"] = "14", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 21000, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1314] = {["id"] = 1314, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 15, ["needLv"] = 1, ["jianzhuLv"] = "15", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 24000, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1315] = {["id"] = 1315, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 16, ["needLv"] = 1, ["jianzhuLv"] = "16", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 27200, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1316] = {["id"] = 1316, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 17, ["needLv"] = 1, ["jianzhuLv"] = "17", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 30600, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1317] = {["id"] = 1317, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 18, ["needLv"] = 1, ["jianzhuLv"] = "18", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 34200, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1318] = {["id"] = 1318, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 19, ["needLv"] = 1, ["jianzhuLv"] = "19", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 38000, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1319] = {["id"] = 1319, ["name"] = "采石场", ["type"] = 4, ["classify"] = 1, ["kind"] = 1, ["lv"] = 20, ["needLv"] = 1, ["jianzhuLv"] = "20", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 42000, ["img"] = "1302", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "挖掘矿石，打造绝世宝石。", ["buildFuncitonId"] = {101, 129}, ["typesOfManufacturing"] = 2, ["order"] = 4, ["canFlip"] = true},
    [1400] = {["id"] = 1400, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 200, ["img"] = "1400", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1401] = {["id"] = 1401, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 2, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 600, ["img"] = "1400", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1402] = {["id"] = 1402, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 3, ["needLv"] = 1, ["jianzhuLv"] = "3", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 1200, ["img"] = "1400", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1403] = {["id"] = 1403, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 4, ["needLv"] = 1, ["jianzhuLv"] = "4", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 2000, ["img"] = "1401", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1404] = {["id"] = 1404, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 5, ["needLv"] = 1, ["jianzhuLv"] = "5", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 3000, ["img"] = "1401", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1405] = {["id"] = 1405, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 6, ["needLv"] = 1, ["jianzhuLv"] = "6", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 4200, ["img"] = "1401", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1406] = {["id"] = 1406, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 7, ["needLv"] = 1, ["jianzhuLv"] = "7", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 5600, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1407] = {["id"] = 1407, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 8, ["needLv"] = 1, ["jianzhuLv"] = "8", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 7200, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1408] = {["id"] = 1408, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 9, ["needLv"] = 1, ["jianzhuLv"] = "9", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 9000, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1409] = {["id"] = 1409, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 10, ["needLv"] = 1, ["jianzhuLv"] = "10", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 11000, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1410] = {["id"] = 1410, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 11, ["needLv"] = 1, ["jianzhuLv"] = "11", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 13200, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1411] = {["id"] = 1411, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 12, ["needLv"] = 1, ["jianzhuLv"] = "12", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 15600, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1412] = {["id"] = 1412, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 13, ["needLv"] = 1, ["jianzhuLv"] = "13", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 18200, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1413] = {["id"] = 1413, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 14, ["needLv"] = 1, ["jianzhuLv"] = "14", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 21000, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1414] = {["id"] = 1414, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 15, ["needLv"] = 1, ["jianzhuLv"] = "15", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 24000, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1415] = {["id"] = 1415, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 16, ["needLv"] = 1, ["jianzhuLv"] = "16", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 27200, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1416] = {["id"] = 1416, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 17, ["needLv"] = 1, ["jianzhuLv"] = "17", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 30600, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1417] = {["id"] = 1417, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 18, ["needLv"] = 1, ["jianzhuLv"] = "18", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 34200, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1418] = {["id"] = 1418, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 19, ["needLv"] = 1, ["jianzhuLv"] = "19", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 38000, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1419] = {["id"] = 1419, ["name"] = "伐木场", ["type"] = 5, ["classify"] = 1, ["kind"] = 1, ["lv"] = 20, ["needLv"] = 1, ["jianzhuLv"] = "20", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 42000, ["img"] = "1402", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = false, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "砍伐木材，建造家园。", ["buildFuncitonId"] = {101, 130}, ["typesOfManufacturing"] = 3, ["order"] = 5, ["canFlip"] = true},
    [1500] = {["id"] = 1500, ["name"] = "宠物房", ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 400, ["img"] = "1500", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "萌萌的小宠物房。", ["buildFuncitonId"] = {100, 101}, ["order"] = 6, ["canFlip"] = true},
    [1501] = {["id"] = 1501, ["name"] = "高级宠物房", ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 400, ["img"] = "1501", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "高端大气的宠物房。", ["buildFuncitonId"] = {100, 101}, ["order"] = 7, ["canFlip"] = true},
    [1502] = {["id"] = 1502, ["name"] = "江南小铺", ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 800, ["img"] = "1502", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "江南女子最爱的游玩地方。", ["buildFuncitonId"] = {100, 101}, ["order"] = 8, ["canFlip"] = true},
    [1503] = {["id"] = 1503, ["name"] = "摘星阁", ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 1800, ["img"] = "1503", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "高端奢华的家园装饰，能为家园锦上添花。", ["buildFuncitonId"] = {100, 101}, ["order"] = 9, ["canFlip"] = true},
    [1504] = {["id"] = 1504, ["name"] = "太液池", ["classify"] = 1, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {5, 5}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 10000, ["img"] = "1504", ["maxCount"] = 1, ["delete"] = false, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "美丽的小池塘您可以夜晚散步舒适心情。", ["buildFuncitonId"] = {100, 101}, ["order"] = 10, ["canFlip"] = true},
    [2000] = {["id"] = 2000, ["name"] = "小路", ["classify"] = 2, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 100, ["img"] = "2000", ["maxCount"] = 100, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "一条静静的小路。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2001] = {["id"] = 2001, ["name"] = "地板", ["classify"] = 2, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 100, ["img"] = "2001", ["maxCount"] = 100, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的小地板。", ["buildFuncitonId"] = {100, 101}, ["order"] = 2, ["canFlip"] = true},
    [2201] = {["id"] = 2201, ["name"] = "露天雪温泉", ["classify"] = 2, ["kind"] = 2, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 400, ["img"] = "2201", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "露天温泉享受大自然的气息。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2202] = {["id"] = 2202, ["name"] = "小假山", ["classify"] = 2, ["kind"] = 2, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 800, ["img"] = "2202", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "磐石本无情，奈何人有意。落落烟波里，回首故人笛。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2203] = {["id"] = 2203, ["name"] = "烟波里假山", ["classify"] = 2, ["kind"] = 2, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 400, ["img"] = "2203", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "磐石本无情，奈何人有意。落落烟波里，回首故人笛。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2204] = {["id"] = 2204, ["name"] = "相思桥", ["classify"] = 2, ["kind"] = 2, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 2400, ["img"] = "2204", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "佳人静憩桥，满帘尽相思。暧昧的桃色软绸缎铺于桥上，美人泪，相思苦，只有这相思桥知吧。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2300] = {["id"] = 2300, ["name"] = "松树", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2300", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 1, ["canFlip"] = true, ["barrier"] = 1},
    [2301] = {["id"] = 2301, ["name"] = "松树", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2301", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 2, ["canFlip"] = true, ["barrier"] = 1},
    [2302] = {["id"] = 2302, ["name"] = "松树", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2302", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 3, ["canFlip"] = true, ["barrier"] = 1},
    [2303] = {["id"] = 2303, ["name"] = "松树", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2303", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 4, ["canFlip"] = true, ["barrier"] = 1},
    [2304] = {["id"] = 2304, ["name"] = "松树", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2304", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 5, ["canFlip"] = true, ["barrier"] = 1},
    [2305] = {["id"] = 2305, ["name"] = "松树", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2305", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 6, ["canFlip"] = true, ["barrier"] = 1},
    [2306] = {["id"] = 2306, ["name"] = "小石头", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2306", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 7, ["canFlip"] = true, ["barrier"] = 1},
    [2307] = {["id"] = 2307, ["name"] = "小石头", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2307", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 8, ["canFlip"] = true, ["barrier"] = 1},
    [2308] = {["id"] = 2308, ["name"] = "摆设大石头", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2308", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 9, ["canFlip"] = true, ["barrier"] = 1},
    [2309] = {["id"] = 2309, ["name"] = "摆设大石头", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2309", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 10, ["canFlip"] = true, ["barrier"] = 1},
    [2310] = {["id"] = 2310, ["name"] = "摆设大石头", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2310", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 11, ["canFlip"] = true, ["barrier"] = 1},
    [2311] = {["id"] = 2311, ["name"] = "摆设大石头", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2311", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 12, ["canFlip"] = true, ["barrier"] = 1},
    [2312] = {["id"] = 2312, ["name"] = "小石头", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2312", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 13, ["canFlip"] = true, ["barrier"] = 1},
    [2313] = {["id"] = 2313, ["name"] = "杂草", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2313", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 14, ["canFlip"] = true, ["barrier"] = 1},
    [2314] = {["id"] = 2314, ["name"] = "杂草", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2314", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 15, ["canFlip"] = true, ["barrier"] = 1},
    [2315] = {["id"] = 2315, ["name"] = "杂草", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2315", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 16, ["canFlip"] = true, ["barrier"] = 1},
    [2316] = {["id"] = 2316, ["name"] = "杂草", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2316", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 17, ["canFlip"] = true, ["barrier"] = 1},
    [2317] = {["id"] = 2317, ["name"] = "杂草", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2317", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 18, ["canFlip"] = true, ["barrier"] = 1},
    [2318] = {["id"] = 2318, ["name"] = "瀑布", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {5, 5}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2318", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 19, ["canFlip"] = true, ["barrier"] = 1},
    [2319] = {["id"] = 2319, ["name"] = "蘑菇", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2319", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 20, ["canFlip"] = true, ["barrier"] = 1},
    [2320] = {["id"] = 2320, ["name"] = "2乘2障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2320", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 21, ["canFlip"] = true, ["barrier"] = 1},
    [2321] = {["id"] = 2321, ["name"] = "2乘2障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2321", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 22, ["canFlip"] = true, ["barrier"] = 1},
    [2322] = {["id"] = 2322, ["name"] = "2乘2障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2322", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 23, ["canFlip"] = true, ["barrier"] = 1},
    [2323] = {["id"] = 2323, ["name"] = "2乘2障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2323", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 24, ["canFlip"] = true, ["barrier"] = 1},
    [2324] = {["id"] = 2324, ["name"] = "2乘2障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2324", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 25, ["canFlip"] = true, ["barrier"] = 1},
    [2325] = {["id"] = 2325, ["name"] = "3乘3障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2325", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 26, ["canFlip"] = true, ["barrier"] = 1},
    [2326] = {["id"] = 2326, ["name"] = "樱花树", ["classify"] = 2, ["kind"] = 3, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 200, ["img"] = "2326", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "云纱山色光潋滟，花容人面魂欲烧。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2327] = {["id"] = 2327, ["name"] = "三春泷樱树", ["classify"] = 2, ["kind"] = 3, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 400, ["img"] = "2327", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "苦蝉待夏半枝鸣，娇樱盼春三日笑。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2328] = {["id"] = 2328, ["name"] = "2乘2障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2328", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 27, ["canFlip"] = true, ["barrier"] = 1},
    [2329] = {["id"] = 2329, ["name"] = "2乘2障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2329", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 28, ["canFlip"] = true, ["barrier"] = 1},
    [2330] = {["id"] = 2330, ["name"] = "2乘2障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2330", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 29, ["canFlip"] = true, ["barrier"] = 1},
    [2331] = {["id"] = 2331, ["name"] = "3乘3障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2331", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 30, ["canFlip"] = true, ["barrier"] = 1},
    [2332] = {["id"] = 2332, ["name"] = "3乘3障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2332", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 31, ["canFlip"] = true, ["barrier"] = 1},
    [2333] = {["id"] = 2333, ["name"] = "3乘3障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2333", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 32, ["canFlip"] = true, ["barrier"] = 1},
    [2334] = {["id"] = 2334, ["name"] = "3乘3障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2334", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 33, ["canFlip"] = true, ["barrier"] = 1},
    [2335] = {["id"] = 2335, ["name"] = "3乘3障碍", ["classify"] = 4, ["kind"] = 1, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "2", ["music"] = 1055, ["isway"] = false, ["size"] = {3, 3}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 0, ["img"] = "2335", ["maxCount"] = 999, ["delete"] = true, ["canBuild"] = false, ["canMoveBuild"] = false, ["jumpBuild"] = false, ["buildDesc"] = "一块安静的石头。", ["order"] = 34, ["canFlip"] = true, ["barrier"] = 1},
    [2800] = {["id"] = 2800, ["name"] = "棋桌", ["classify"] = 2, ["kind"] = 4, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 400, ["img"] = "2800", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "双人对弈棋盘。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2801] = {["id"] = 2801, ["name"] = "石凳", ["classify"] = 2, ["kind"] = 4, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 200, ["img"] = "2801", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "对弈静坐石凳。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2802] = {["id"] = 2802, ["name"] = "石灯", ["classify"] = 2, ["kind"] = 4, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 200, ["img"] = "2802", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "夜幕下闪烁着微微灯光的的小石灯~", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2803] = {["id"] = 2803, ["name"] = "花园路灯", ["classify"] = 2, ["kind"] = 4, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 400, ["img"] = "2803", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "夜幕下闪烁着霓虹色彩，为花园的路人照亮黑暗。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2804] = {["id"] = 2804, ["name"] = "红木塔灯", ["classify"] = 2, ["kind"] = 4, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {1, 1}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 400, ["img"] = "2804", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "红灯夜明昙华正盛，共饮逍遥一世悠然。", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true},
    [2805] = {["id"] = 2805, ["name"] = "长相思亭宇", ["classify"] = 2, ["kind"] = 4, ["lv"] = 1, ["needLv"] = 1, ["jianzhuLv"] = "1", ["music"] = 1055, ["isway"] = false, ["size"] = {2, 2}, ["particle"] = {1000}, ["needMoney"] = 0, ["needType"] = 1, ["prosperity"] = 1600, ["img"] = "2805", ["maxCount"] = 10, ["delete"] = true, ["canBuild"] = true, ["canMoveBuild"] = true, ["jumpBuild"] = false, ["buildDesc"] = "细雨绵绵时给男女邂逅的专用小亭宇~不少年轻男女在此找到真爱了呢！", ["buildFuncitonId"] = {100, 101}, ["order"] = 1, ["canFlip"] = true}
}

return data