--
-- 卡牌动作表.csv
-- 信息条编号 = id
-- 名字 = name
-- 动作文件名 = fileName

local data = {
    [100] = {["id"] = 100, ["name"] = "攻击", ["fileName"] = "fight_action_fotiaoqiangattack"},
    [1002] = {["id"] = 1002, ["name"] = "一鸣惊人受伤", ["fileName"] = "fight_action_beida01"},
    [2000] = {["id"] = 2000, ["name"] = "闭月羞花攻击", ["fileName"] = "fight_action_fotiaoqiangattack"},
    [2001] = {["id"] = 2001, ["name"] = "闭月羞花受击", ["fileName"] = "fight_action_beida02"},
    [2002] = {["id"] = 2002, ["name"] = "佛跳墙攻击", ["fileName"] = "fight_action_fotiaoqiangattack"},
    [2003] = {["id"] = 2003, ["name"] = "佛跳墙受击", ["fileName"] = "fight_action_beileipi"},
    [2004] = {["id"] = 2004, ["name"] = "晴天霹雳攻击", ["fileName"] = "fight_action_qingtianpili"},
    [2005] = {["id"] = 2005, ["name"] = "晴天霹雳受击", ["fileName"] = "fight_action_beileipi"},
    [2006] = {["id"] = 2006, ["name"] = "暗杀", ["fileName"] = "fight_action_ansha"},
    [2007] = {["id"] = 2007, ["name"] = "暗杀", ["fileName"] = "fight_action_beiansha"},
    [2008] = {["id"] = 2008, ["name"] = "一鸣惊人", ["fileName"] = "fight_action_yimingjingren"},
    [2009] = {["id"] = 2009, ["name"] = "河东狮吼", ["fileName"] = "fight_action_attack01"},
    [2010] = {["id"] = 2010, ["name"] = "河东狮吼", ["fileName"] = "fight_action_beida01"},
    [2011] = {["id"] = 2011, ["name"] = "河东狮吼", ["fileName"] = "fight_action_xuli"},
    [2012] = {["id"] = 2012, ["name"] = "霓虹飞天蓄力", ["fileName"] = "fight_action_xuli_01"},
    [2013] = {["id"] = 2013, ["name"] = "霓虹飞天攻击", ["fileName"] = "fight_action_attack01"},
    [2014] = {["id"] = 2014, ["name"] = "霓虹飞天受击", ["fileName"] = "fight_action_beileipi"},
    [2015] = {["id"] = 2015, ["name"] = "飞针攻击", ["fileName"] = "fight_action_yimingjingren"},
    [2016] = {["id"] = 2016, ["name"] = "飞针受击", ["fileName"] = "fight_action_beileipi"},
    [2017] = {["id"] = 2017, ["name"] = "飞针蓄力", ["fileName"] = "fight_action_xuli"},
    [2018] = {["id"] = 2018, ["name"] = "枯木逢春蓄力", ["fileName"] = "fight_action_xuli"},
    [2019] = {["id"] = 2019, ["name"] = "枯木逢春受击", ["fileName"] = "fight_action_bzhiliao"},
    [2020] = {["id"] = 2020, ["name"] = "绵里藏针蓄力", ["fileName"] = "fight_action_xuli"},
    [2021] = {["id"] = 2021, ["name"] = "绵里藏针攻击", ["fileName"] = "fight_action_mianlicangzhen"},
    [2023] = {["id"] = 2023, ["name"] = "绵里藏针受击动作", ["fileName"] = "fight_action_beida01"},
    [2024] = {["id"] = 2024, ["name"] = "流言弹幕", ["fileName"] = "fight_action_yuangong01"},
    [2025] = {["id"] = 2025, ["name"] = "流言受伤", ["fileName"] = "fight_action_beida02"},
    [2026] = {["id"] = 2026, ["name"] = "龙凤在天攻击", ["fileName"] = "fight_action_fotiaoqiangattack"},
    [2027] = {["id"] = 2027, ["name"] = "龙凤在天蓄力", ["fileName"] = "fight_action_xuli"},
    [2028] = {["id"] = 2028, ["name"] = "龙凤在天受击", ["fileName"] = "fight_action_beida02"},
    [2030] = {["id"] = 2030, ["name"] = "杨枝甘露攻击", ["fileName"] = "fight_action_fotiaoqiangattack"},
    [2031] = {["id"] = 2031, ["name"] = "杨枝甘露蓄力", ["fileName"] = "fight_action_xuli"},
    [2032] = {["id"] = 2032, ["name"] = "杨枝甘露受击", ["fileName"] = "fight_action_fuhuo"},
    [2033] = {["id"] = 2033, ["name"] = "满汉全席受击", ["fileName"] = "fight_action_bzhiliao"},
    [2034] = {["id"] = 2034, ["name"] = "满汉全席蓄力", ["fileName"] = "fight_action_xuli"},
    [2035] = {["id"] = 2035, ["name"] = "挥墨受击", ["fileName"] = "fight_action_beida02"},
    [2036] = {["id"] = 2036, ["name"] = "挥墨攻击", ["fileName"] = "fight_action_luomo"},
    [2037] = {["id"] = 2037, ["name"] = "挥墨蓄力", ["fileName"] = "fight_action_xuli"},
    [2038] = {["id"] = 2038, ["name"] = "爆炒受击", ["fileName"] = "fight_action_beileipi"},
    [2039] = {["id"] = 2039, ["name"] = "爆炒攻击", ["fileName"] = "fight_action_qingtianpili"},
    [2040] = {["id"] = 2040, ["name"] = "丁氏猪肉受击", ["fileName"] = "fight_action_beileipi"},
    [2041] = {["id"] = 2041, ["name"] = "丁氏猪肉攻击", ["fileName"] = "fight_action_dingshizhurou"},
    [2042] = {["id"] = 2042, ["name"] = "成鱼落雁受击", ["fileName"] = "fight_action_beileipi"},
    [2043] = {["id"] = 2043, ["name"] = "成鱼落雁蓄力", ["fileName"] = "fight_action_xuli"},
    [2044] = {["id"] = 2044, ["name"] = "满汉全席攻击", ["fileName"] = "fight_action_fotiaoqiangattack"},
    [2045] = {["id"] = 2045, ["name"] = "秉烛达旦受击", ["fileName"] = "fight_action_beileipi"},
    [2046] = {["id"] = 2046, ["name"] = "秉烛达旦蓄力", ["fileName"] = "fight_action_xuli"},
    [2047] = {["id"] = 2047, ["name"] = "秉烛达旦攻击", ["fileName"] = "fight_action_qingtianpili"},
    [2048] = {["id"] = 2048, ["name"] = "道山学海受击", ["fileName"] = "fight_action_beida02"},
    [2049] = {["id"] = 2049, ["name"] = "道山学海蓄力", ["fileName"] = "fight_action_xuli"},
    [2050] = {["id"] = 2050, ["name"] = "道山学海攻击", ["fileName"] = "fight_action_qingtianpili"},
    [2051] = {["id"] = 2051, ["name"] = "一次性加血蓄力", ["fileName"] = "fight_action_xuli"},
    [2052] = {["id"] = 2052, ["name"] = "一次性加血受击", ["fileName"] = "fight_action_fuhuo"},
    [2053] = {["id"] = 2053, ["name"] = "下毒受击", ["fileName"] = "fight_action_beida02"},
    [2054] = {["id"] = 2054, ["name"] = "下毒蓄力", ["fileName"] = "fight_action_xuli"},
    [2055] = {["id"] = 2055, ["name"] = "普通攻击", ["fileName"] = "fight_action_attack01"},
    [2056] = {["id"] = 2056, ["name"] = "普通攻击受击", ["fileName"] = "fight_action_beileipi"},
    [2060] = {["id"] = 2060, ["name"] = "兵临城下蓄力", ["fileName"] = "fight_action_xuli_01"},
    [2061] = {["id"] = 2061, ["name"] = "兵临城下受击", ["fileName"] = "fight_action_beida02"},
    [2062] = {["id"] = 2062, ["name"] = "凤鸣失蓄力", ["fileName"] = "fight_action_xuli_01"},
    [2063] = {["id"] = 2063, ["name"] = "凤鸣失受击", ["fileName"] = "fight_action_beida02"},
    [2064] = {["id"] = 2064, ["name"] = "空灵闪蓄力", ["fileName"] = "fight_action_xuli_01"},
    [2065] = {["id"] = 2065, ["name"] = "空灵闪受击", ["fileName"] = "fight_action_beida02"},
    [2066] = {["id"] = 2066, ["name"] = "醉芙蓉受击", ["fileName"] = "fight_action_beida02"},
    [2067] = {["id"] = 2067, ["name"] = "双飞火受击", ["fileName"] = "fight_action_beida02"},
    [2068] = {["id"] = 2068, ["name"] = "百蛊噬魂蓄力", ["fileName"] = "fight_action_xuli_01"},
    [2069] = {["id"] = 2069, ["name"] = "百蛊噬魂受击", ["fileName"] = "fight_action_beida02"},
    [2070] = {["id"] = 2070, ["name"] = "闪现", ["fileName"] = "fight_action_shanbi"},
    [2071] = {["id"] = 2071, ["name"] = "出其不意受击", ["fileName"] = "fight_action_beida02"},
    [2072] = {["id"] = 2072, ["name"] = "分花抚柳受击", ["fileName"] = "fight_action_beida02"},
    [2098] = {["id"] = 2098, ["name"] = "满汉全席攻击", ["fileName"] = "fight_action_qingtianpili"},
    [2099] = {["id"] = 2099, ["name"] = "枯木逢春攻击", ["fileName"] = "fight_action_jiaxue"},
    [9999] = {["id"] = 9999, ["name"] = "死亡动作", ["fileName"] = "fight_action_dead02"}
}

return data